export const SEARCH_FLIGHTS = "SEARCH_FLIGHTS";
export const SEARCH_HOTELS = "SEARCH_HOTELS";
export const BOOK_FLIGHT = "BOOK_FLIGHT";
export const BOOK_HOTEL = "BOOK_HOTEL";
export const BOOKING_ERROR = "BOOKING_ERROR";
export const CLEAR_FLIGHT_RESULTS = "CLEAR_FLIGHT_RESULTS";
export const CLEAR_HOTEL_RESULTS = "CLEAR_HOTEL_RESULTS";
export const SET_LOADING = "BOOKING_SET_LOADING";
