export const TRANSLATE_TEXT = "TRANSLATE_TEXT";
export const GET_LANGUAGES = "GET_LANGUAGES";
export const TRANSLATOR_ERROR = "TRANSLATOR_ERROR";
export const CLEAR_TRANSLATION = "CLEAR_TRANSLATION";
export const SET_LOADING = "TRANSLATOR_SET_LOADING";
