export const GET_CURRENT_WEATHER = "GET_CURRENT_WEATHER";
export const GET_FORECAST = "GET_FORECAST";
export const WEATHER_ERROR = "WEATHER_ERROR";
export const CLEAR_WEATHER = "CLEAR_WEATHER";
export const SET_LOADING = "WEATHER_SET_LOADING";
